import { describe, expect, it, vi } from 'vitest'

import { fetchTranscriptFromCaptionTracks } from '../packages/core/src/content/transcript/providers/youtube/captions.js'

describe('YouTube captionTracks: skipAutoGenerated', () => {
  it('skips automaticCaptions + ASR tracks when skipAutoGenerated is true', async () => {
    const fetchImpl = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input)
      if (url.startsWith('https://example.com/manual')) {
        return new Response(JSON.stringify({ events: [{ segs: [{ utf8: 'Hello manual' }] }] }))
      }
      if (url.startsWith('https://example.com/asr')) {
        return new Response(JSON.stringify({ events: [{ segs: [{ utf8: 'Hello ASR' }] }] }))
      }
      return new Response('', { status: 404 })
    }) as unknown as typeof fetch

    const html = `ytInitialPlayerResponse = ${JSON.stringify({
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [{ languageCode: 'en', kind: '', baseUrl: 'https://example.com/manual' }],
          automaticCaptions: [{ languageCode: 'en', kind: 'asr', baseUrl: 'https://example.com/asr' }],
        },
      },
    })}`

    const transcript = await fetchTranscriptFromCaptionTracks(fetchImpl, {
      html,
      originalUrl: 'https://www.youtube.com/watch?v=abcdefghijk',
      videoId: 'abcdefghijk',
      skipAutoGenerated: true,
    })

    expect(transcript).toBe('Hello manual')
    expect(fetchImpl).toHaveBeenCalled()
    expect(fetchImpl.mock.calls.map((call) => String(call[0]))).toEqual(
      expect.not.arrayContaining([expect.stringContaining('example.com/asr')])
    )
  })

  it('returns null when only auto captions exist and skipAutoGenerated is true', async () => {
    const fetchImpl = vi.fn(async () => new Response('')) as unknown as typeof fetch

    const html = `ytInitialPlayerResponse = ${JSON.stringify({
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [],
          automaticCaptions: [{ languageCode: 'en', kind: 'asr', baseUrl: 'https://example.com/asr' }],
        },
      },
    })}`

    const transcript = await fetchTranscriptFromCaptionTracks(fetchImpl, {
      html,
      originalUrl: 'https://www.youtube.com/watch?v=abcdefghijk',
      videoId: 'abcdefghijk',
      skipAutoGenerated: true,
    })

    expect(transcript).toBeNull()
    expect(fetchImpl).not.toHaveBeenCalled()
  })

  it('uses auto captions when skipAutoGenerated is false and no manual captions exist', async () => {
    const fetchImpl = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input)
      if (url.includes('example.com/asr')) {
        return new Response(JSON.stringify({ events: [{ segs: [{ utf8: 'Hello ASR' }] }] }))
      }
      return new Response('', { status: 404 })
    }) as unknown as typeof fetch

    const html = `ytInitialPlayerResponse = ${JSON.stringify({
      captions: {
        playerCaptionsTracklistRenderer: {
          automaticCaptions: [{ languageCode: 'en', kind: 'asr', baseUrl: 'https://example.com/asr' }],
        },
      },
    })}`

    const transcript = await fetchTranscriptFromCaptionTracks(fetchImpl, {
      html,
      originalUrl: 'https://www.youtube.com/watch?v=abcdefghijk',
      videoId: 'abcdefghijk',
      skipAutoGenerated: false,
    })

    expect(transcript).toBe('Hello ASR')
    expect(fetchImpl).toHaveBeenCalled()
  })
})

