function byId<T extends HTMLElement>(id: string): T {
  const el = document.getElementById(id);
  if (!el) throw new Error(`Missing #${id}`);
  return el as T;
}

export function getOptionsElements() {
  const tabsRoot = byId<HTMLDivElement>("tabs");

  return {
    formEl: byId<HTMLFormElement>("form"),
    statusEl: byId<HTMLSpanElement>("status"),
    tokenEl: byId<HTMLInputElement>("token"),
    daemonPortEl: byId<HTMLInputElement>("daemonPort"),
    daemonCapabilityStatusEl: byId<HTMLDivElement>("daemonCapabilityStatus"),
    daemonPermissionEnableBtn: byId<HTMLButtonElement>("daemonPermissionEnable"),
    daemonFieldsEl: byId<HTMLDivElement>("daemonFields"),
    tokenCopyBtn: byId<HTMLButtonElement>("tokenCopy"),
    summaryRuntimeModeRoot: byId<HTMLDivElement>("summaryRuntimeMode"),
    providerEl: byId<HTMLSelectElement>("provider"),
    providerApiKeyEl: byId<HTMLInputElement>("providerApiKey"),
    providerBaseUrlEl: byId<HTMLInputElement>("providerBaseUrl"),
    modelPresetEl: byId<HTMLSelectElement>("modelPreset"),
    modelCustomEl: byId<HTMLInputElement>("modelCustom"),
    languagePresetEl: byId<HTMLSelectElement>("languagePreset"),
    languageCustomEl: byId<HTMLInputElement>("languageCustom"),
    promptOverrideEl: byId<HTMLTextAreaElement>("promptOverride"),
    autoToggleRoot: byId<HTMLDivElement>("autoToggle"),
    maxCharsEl: byId<HTMLInputElement>("maxChars"),
    hoverPromptEl: byId<HTMLTextAreaElement>("hoverPrompt"),
    hoverPromptResetBtn: byId<HTMLButtonElement>("hoverPromptReset"),
    chatToggleRoot: byId<HTMLDivElement>("chatToggle"),
    automationToggleRoot: byId<HTMLDivElement>("automationToggle"),
    automationPermissionsBtn: byId<HTMLButtonElement>("automationPermissions"),
    userScriptsNoticeEl: byId<HTMLDivElement>("userScriptsNotice"),
    skillsExportBtn: byId<HTMLButtonElement>("skillsExport"),
    skillsImportBtn: byId<HTMLButtonElement>("skillsImport"),
    skillsSearchEl: byId<HTMLInputElement>("skillsSearch"),
    skillsListEl: byId<HTMLDivElement>("skillsList"),
    skillsEmptyEl: byId<HTMLDivElement>("skillsEmpty"),
    skillsConflictsEl: byId<HTMLDivElement>("skillsImportConflicts"),
    hoverSummariesToggleRoot: byId<HTMLDivElement>("hoverSummariesToggle"),
    summaryTimestampsToggleRoot: byId<HTMLDivElement>("summaryTimestampsToggle"),
    slidesParallelToggleRoot: byId<HTMLDivElement>("slidesParallelToggle"),
    slideRuntimeModeRoot: byId<HTMLDivElement>("slideRuntimeMode"),
    slidesOcrToggleRoot: byId<HTMLDivElement>("slidesOcrToggle"),
    extendedLoggingToggleRoot: byId<HTMLDivElement>("extendedLoggingToggle"),
    autoCliFallbackToggleRoot: byId<HTMLDivElement>("autoCliFallbackToggle"),
    autoCliOrderEl: byId<HTMLInputElement>("autoCliOrder"),
    requestModeEl: byId<HTMLSelectElement>("requestMode"),
    firecrawlModeEl: byId<HTMLSelectElement>("firecrawlMode"),
    markdownModeEl: byId<HTMLSelectElement>("markdownMode"),
    preprocessModeEl: byId<HTMLSelectElement>("preprocessMode"),
    youtubeModeEl: byId<HTMLSelectElement>("youtubeMode"),
    transcriberEl: byId<HTMLSelectElement>("transcriber"),
    timeoutEl: byId<HTMLInputElement>("timeout"),
    retriesEl: byId<HTMLInputElement>("retries"),
    maxOutputTokensEl: byId<HTMLInputElement>("maxOutputTokens"),
    pickersRoot: byId<HTMLDivElement>("pickersRoot"),
    fontFamilyEl: byId<HTMLInputElement>("fontFamily"),
    fontSizeEl: byId<HTMLInputElement>("fontSize"),
    buildInfoEl: document.getElementById("buildInfo"),
    daemonStatusEl: byId<HTMLDivElement>("daemonStatus"),
    browserCacheStatusEl: byId<HTMLDivElement>("browserCacheStatus"),
    browserCacheClearBtn: byId<HTMLButtonElement>("browserCacheClear"),
    logsSourceEl: byId<HTMLSelectElement>("logsSource"),
    logsTailEl: byId<HTMLInputElement>("logsTail"),
    logsRefreshBtn: byId<HTMLButtonElement>("logsRefresh"),
    logsAutoEl: byId<HTMLInputElement>("logsAuto"),
    logsOutputEl: byId<HTMLDivElement>("logsOutput"),
    logsRawEl: byId<HTMLPreElement>("logsRaw"),
    logsTableEl: byId<HTMLTableElement>("logsTable"),
    logsParsedEl: byId<HTMLInputElement>("logsParsed"),
    logsMetaEl: byId<HTMLDivElement>("logsMeta"),
    processesRefreshBtn: byId<HTMLButtonElement>("processesRefresh"),
    processesAutoEl: byId<HTMLInputElement>("processesAuto"),
    processesShowCompletedEl: byId<HTMLInputElement>("processesShowCompleted"),
    processesLimitEl: byId<HTMLInputElement>("processesLimit"),
    processesStreamEl: byId<HTMLSelectElement>("processesStream"),
    processesTailEl: byId<HTMLInputElement>("processesTail"),
    processesMetaEl: byId<HTMLDivElement>("processesMeta"),
    processesTableEl: byId<HTMLTableElement>("processesTable"),
    processesLogsTitleEl: byId<HTMLDivElement>("processesLogsTitle"),
    processesLogsCopyBtn: byId<HTMLButtonElement>("processesLogsCopy"),
    processesLogsOutputEl: byId<HTMLPreElement>("processesLogsOutput"),
    tabsRoot,
    tabButtons: Array.from(tabsRoot.querySelectorAll<HTMLButtonElement>("[data-tab]")),
    tabPanels: Array.from(document.querySelectorAll<HTMLElement>("[data-tab-panel]")),
    logsLevelInputs: Array.from(
      document.querySelectorAll<HTMLInputElement>("input[data-log-level]"),
    ),
  };
}
